name: Node.js CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, homolog, develop]
jobs:
  test-ci:
    name: Test CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

  deploy-development:
    needs: test-ci
    name: Develop Deploy
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    concurrency: deploy-to-test
    environment: test
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm run lint --if-present
      - run: npm run lint:fix --if-present
      - run: npm run test --if-present
      - run: npm run build
      - run: echo "✅ Deploy"

  deploy-homolog:
    needs: test-ci
    if: github.ref == 'refs/heads/homolog'
    name: Homolog Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-to-test
    environment: test
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm run lint --if-present
      - run: npm run lint:fix --if-present
      - run: npm run build
      - run: echo "✅ Deploy"

  deploy-production:
    needs: test-ci
    if: github.ref == 'refs/heads/master'
    name: Master Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-to-test
    environment: test
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm run lint --if-present
      - run: npm run lint:fix --if-present
      - run: npm run build
      - run: echo "✅ Deploy"
